apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflared-tunnel-http-exits
  namespace: argocd
spec:
  generators:
    - list:
        # 出口を生成するリスト。
        # オンプレネットワーク内で HTTP で公開されているサービスを外部に露出したい時は、
        # このリストに
        #   - トンネル名の suffix として使われる文字列 (name)
        #   - 露出されるサービスが外部から見えるようになるドメイン (external-hostname)
        #   - Pod から見た、サービスが公開されている authority ({{domain-name}}:{{port}} の形式の文字列) (internal-authority)
        # の三つのプロパティを持つ要素を追加すればよい。
        elements:
          - name: server-list
            external-hostname: server-list.commet.jp
            internal-authority: 192.168.0.11:30000
  template:
    metadata:
      name: "cloudflared-tunnel-http-exit-{{name}}"
      namespace: argocd
    spec:
      project: cloudflared-tunnel-exits
      source:
        repoURL: https://github.com/GiganticMinecraft/seichi_infra
        targetRevision: "main"
        path: seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/cloudflared-tunnel
        helm:
          # サービス一つに対してトンネルを一つずつ生やす
          releaseName: cloudflared-tunnel-http-exit-{{name}}
          values: |
            installationName: {{name}}
            tunnelNamePrefix: "commet-onp-k8s-http-"
            tunnelCredentialSecretName: "cloudflared-tunnel-cert"
            tunnelConfigContent: |
              ingress:
                - hostname: {{external-hostname}}
                  service: "http://{{internal-authority}}"
                # Catch-all service
                - service: http_status:404

      destination:
        server: https://kubernetes.default.svc
        namespace: cloudflared-tunnel-exits
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ServerSideApply=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m