apiVersion: apps/v1
kind: Deployment
metadata:
  name: next
  labels:
    app: next
  namespace: server-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/commet-431413/server-list/app:latest
          name: next
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-url
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: server-list-image-pull-secrets