apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitess-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/planetscale/vitess-operator.git
    targetRevision: main
    path: test/endtoend/operator
    directory:
      include: "operator.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: server-list
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true